---

- name: f5_tasks
  hosts: bigip1
  vars_files:
    - ../group_vars/f5-bigip.yaml
  tasks:
    - name: Create REP pools
      bigip_pool:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        partition: Common
      with_items:
       - "{{ virtual_server.pool }}"
      delegate_to: localhost
    - name: Add members to pools
      bigip_pool_member:
        provider: "{{ provider }}"
        host: "{{ item.host }}"
        name: "{{ item.host }}"
        pool: "{{ item.pool }}"
        port: "{{ item.port }}"
      with_items:
        - "{{ virtual_server.pool.members }}"
      delegate_to: localhost
    - name: Create virtual servers
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip
        destination: 172.16.10.108
        name: "{{ item.name }}"
        pool: "{{ item.name }}"
        port: "{{ item.port }}"
        snat: Automap
        profiles:
          - http
          - clientssl
      with_items:
        - "{{ virtual_server }}"
      delegate_to: localhost

    # - name: Create node
      # bigip_node:
        # name: {{ item }}
        # host: {{ item }}
        # state: present
        # partition: Common
        # provider: "{{ provider }}"
      # with_items:
        # - {{ var.node }}
      # delegate_to: localhost
